#
# This first loadbalancer service requests an IP from a specific address-pool
#
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-lb-service-01
  namespace: ingress
  annotations:
    metallb.universe.tf/address-pool: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  type: LoadBalancer

#
# This second loadbalancer service specifies the IP address to be used
#
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-lb-service-02
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  loadBalancerIP: 192.168.1.81
  type: LoadBalancer
