---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-lb-service
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  type: LoadBalancer
